# -*- coding: utf-8 -*-
"""Tensorflow 1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/155vG3yulRsKNwIfOKQ-b3aKDYRqSYfwD
"""



ximport os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'
import tensorflow as tf

# Initialization of Tensors
x = tf.constant(4, shape=(1,1), dtype=tf.float32)
print(x)

y = tf.constant([[1,2,3], [4,5,6]])
print(y)
# This code prints a 2 by 3 tensor.
# Two rows, each containing 3 columns

# We can obtain a 3 by 3 matrix of values of 1
d = tf.ones((3, 3))
print(d)

l = tf.zeros((2, 3))
print(l)

f = tf.eye(3)
print(f)

# Prints 1 in the diagonal, and 0 everywhere else

t = tf.random.normal((3, 3), mean=0, stddev=1)
print(t)

m = tf.random.uniform((1, 3), minval=0, maxval=1)
print(m)

# Something similar to the python range function

s = tf.range(start=1, limit=10, delta=2)
print(s)

s = tf.cast(s, dtype=tf.float64)

"""# **Mathematical operations**"""

# Addition
b = tf.constant([1, 2, 3])
a = tf.constant([7, 8, 9])

c = tf.add(b, a)
print(c)

c = tf.multiply(b, a)
print(c)

c = tf.divide(b, a)
print(c)

c = tf.tensordot(b, a, axes=1)
print(c)

c = tf.reduce_sum(b*a, axis=0)
print(c)

c = b ** 5
print(c)

"""# **Matrix** **multiplication**


"""

x = tf.random.normal((2, 3))
y = tf.random.normal((3, 4))
z = tf.matmul(x, y)

print(z)

"""# **Indexing** **a** **tensor**"""

x = tf.constant([0, 1, 1, 2, 3, 1, 2, 3])
print(x[:])
print(x[1:]) # Excludes the first index

print(x[1: 3])

print(x[::2]) # Skips values after one value in the list

# We can print in reverse
print(x[::-1])



"""# **Reshaping** **a** **matrix**"""

X =tf.range(9)
print(X)

X =tf.reshape(X, (3, 3))
print(X)

# Reshapes the matrix to a 3 by 3

X = tf.transpose(X, perm=[1, 0])
print(X)

# Flips and interchanges the columns and rows of the matrix.